### ISSUE TITLE
Replace Images

### ISSUE THREAD

**Issue by Damian-R-Smith** [plus10io/website#1]
Images on the website need to be changed for some newer ones with a better camera.

**Comment by plus10cork** [comment]
I can bring my SLR in next week and we can get a few shots. Also have some devices we can put up on the wall and get some shots for the ODL. Two birds and that :stuck_out_tongue_closed_eyes:

**Comment by Damian-R-Smith** [comment]
Perfect!

**Comment by Damian-R-Smith** [comment]
Will we get the ball rolling on this on? Some fresh images are badly needed!
