### ISSUE TITLE
Mentor tab does nothing?

### ISSUE THREAD

**Issue by Damian-R-Smith** [plus10io/website#11]
What will we do with it?

**Comment by Damian-R-Smith** [comment]
I commented out this tab untill we have a plan for it.

**Comment by oneillray** [comment]
Maybe we can change it to freelancers to and give ourselves a profile each?

**Comment by Damian-R-Smith** [comment]
Ya was thinking something similar, maybe calling it "people" and having a bio of anyone available and their various skills
