### ISSUE TITLE
Other hosting options? What do you think?

### ISSUE THREAD

**Issue by Damian-R-Smith** [plus10io/website#14]
Github pages is pretty fecking restrictive on what we can use on our site. Although the site is basically static we still need some flexibility for php and other scripts in some spots.

Might try to move the app to heroku? Its allows dynamic apps, custom domains and we can still use git to work on the code? I assume I'll need the azure account details for fiddling around with the domain stuff. Could you pass those on to me if you do?

**Comment by plus10cork** [comment]
We’ll have a chat about this next week. I’ve no problem with hosting it on Heruko. We’ll go through everything next week on what we need and don’t need on the website content wise. I can start on the design and built out the front-end if you can handle the scripting
